// Biblioteca compartilhada @arruda/rbac-client
export * from './auth/AuthProvider';
export * from './auth/useArrudaAuth';
export * from './permissions/usePermissions';
export * from './session/SessionManager';
export * from './components/ProtectedRoute';
export * from './components/PermissionGate';
export * from './components/FrontendGuard';
export * from './components/SoftFrontendGuard';
export * from './types';
export * from './utils/logger';
